language: elixir
elixir:
  - 1.6
  - 1.5
  - 1.4
  - 1.3
otp_release:
  - 20.2
  - 19.3
  - 18.3
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 18.3
    - elixir: 1.3
      otp_release: 20.2
script:
  - mix test
  - mix credo